#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
============================================================
seed_plan.py — load a validated plan into the mail engine
------------------------------------------------------------
  python seed_plan.py plans/plan-180.json                → seed-L1-180.sql
  python seed_plan.py plans/plan-180.json --sqlite engine.db
  python seed_plan.py plans/*.json --sqlite engine.db    (several at once)

The SQL targets the schema from plan-engine-design.md §3-4 and is valid
for SQLite / Cloudflare D1 / Postgres (swap nothing).
Idempotent: re-seeding the same plan_id+version replaces its pills.
============================================================
"""

import argparse, glob, json, os, sqlite3, sys

DDL = """
CREATE TABLE IF NOT EXISTS pills (
  id            TEXT PRIMARY KEY,
  plan_id       TEXT NOT NULL,
  plan_version  TEXT NOT NULL,
  day           INTEGER NOT NULL,
  topic         TEXT NOT NULL,
  title         TEXT NOT NULL,
  concept       TEXT NOT NULL,
  exam_tips     TEXT,              -- JSON array
  formula       TEXT,
  question      TEXT NOT NULL      -- JSON: {stem, choices[], correct_key}
);
CREATE UNIQUE INDEX IF NOT EXISTS uniq_pill
  ON pills (plan_id, plan_version, day);

CREATE TABLE IF NOT EXISTS plans (
  plan_id       TEXT NOT NULL,
  plan_version  TEXT NOT NULL,
  name          TEXT,
  days          INTEGER NOT NULL,
  generated_at  TEXT,
  PRIMARY KEY (plan_id, plan_version)
);
"""

def q(s):
    """SQL string literal (single quotes doubled)."""
    return "'" + str(s).replace("'", "''") + "'"

def plan_rows(plan):
    pid, ver = plan["plan_id"], plan["version"]
    yield (f"DELETE FROM pills WHERE plan_id={q(pid)} AND plan_version={q(ver)};")
    yield (f"INSERT OR REPLACE INTO plans VALUES "
           f"({q(pid)},{q(ver)},{q(plan.get('name',''))},"
           f"{int(plan['days'])},{q(plan.get('generated_at',''))});")
    for p in plan["pills"]:
        yield ("INSERT INTO pills VALUES ("
               f"{q(p['id'])},{q(pid)},{q(ver)},{int(p['day'])},{q(p['topic'])},"
               f"{q(p['title'])},{q(p['concept'])},"
               f"{q(json.dumps(p.get('exam_tips') or [], ensure_ascii=False))},"
               f"{q(p.get('formula')) if p.get('formula') else 'NULL'},"
               f"{q(json.dumps(p['question'], ensure_ascii=False))});")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("plan_json", nargs="+", help="one or more plan JSON files (globs ok)")
    ap.add_argument("--sqlite", metavar="DB", help="apply directly into this SQLite file")
    a = ap.parse_args()

    files = [f for pat in a.plan_json for f in (glob.glob(pat) or [pat])]
    conn = None
    if a.sqlite:
        conn = sqlite3.connect(a.sqlite)
        conn.executescript(DDL)

    for path in files:
        try:
            plan = json.load(open(path, encoding="utf-8"))
        except Exception as e:
            sys.exit(f"✗ {path}: {e}")
        rows = list(plan_rows(plan))

        if conn:
            for stmt in rows:
                conn.execute(stmt)
            conn.commit()
            print(f"✔ {plan['plan_id']} {plan['version']} → {a.sqlite} "
                  f"({len(plan['pills'])} pills)")
        else:
            out = f"seed-{plan['plan_id']}.sql"
            with open(out, "w", encoding="utf-8") as f:
                f.write("-- generated by seed_plan.py — apply with any SQL client\n")
                f.write(DDL + "\n")
                f.write("\n".join(rows) + "\n")
            print(f"✔ {plan['plan_id']} {plan['version']} → {out} "
                  f"({len(plan['pills'])} pills)")
            print(f"   D1:  wrangler d1 execute <DB_NAME> --file={out}")

    if conn:
        n = conn.execute("SELECT COUNT(*) FROM pills").fetchone()[0]
        print(f"   DB now holds {n} pills total.")
        conn.close()

if __name__ == "__main__":
    main()
